name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bun vite build
        env:
          DB_ACCESS_TOKEN: ${{ secrets.DB_ACCESS_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist